# vim:ft=kitty
#: This is a template that can be used to create new kitty themes.
#: Theme files should start with a metadata block consisting of
#: lines beginning with ##. All metadata fields are optional.
## name: Box
## author: D3vil0p3r
## license: GPLv3
## blurb: Hack The Box inspired colorscheme.
#: All the settings below are colors, which you can choose to modify, or use the
#: defaults. You can also add non-color based settings if needed but note that
#: these will not work with using kitty @ set-colors with this theme. For a
#: reference on what these settings do see https://sw.kovidgoyal.net/kitty/conf/


#: OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color   system


#: The basic colors
foreground                      #80FF00
selection_foreground            #80FF00
background                      #141414
selection_background            #1A7FCC


#: Cursor colors
cursor                          #80FF00
cursor_text_color               #111111


#: URL underline color when hovering with mouse
url_color                       #25D0AB


#: kitty window border colors and terminal bell colors
active_border_color             #66CC00
inactive_border_color           #CCCCCC
bell_border_color               #E8711A
visual_bell_color               none


#: Tab bar colors
active_tab_foreground           #000000
active_tab_background           #80FF00
inactive_tab_foreground         #FFFF00
inactive_tab_background         #1A7FCC
tab_bar_background              none
tab_bar_margin_color            none


#: Colors for marks (marked text in the terminal)
mark1_foreground black
mark1_background #70BDAD
mark2_foreground black
mark2_background #C78C5C
mark3_foreground black
mark3_background #B84DB8


#: The basic 16 colors
#: black
color0  #000000
color8  #4D4D4D
#: red
color1  #CC1414
color9  #E84D4D
#: green
color2  #0DAD0D
color10 #3DD63D
#: yellow
color3  #CCCC00
color11 #E6E666
#: blue
color4  #143DB8
color12 #4D7AE8
#: magenta
color5  #8A14C2
color13 #B84DE8
#: cyan
color6  #0DA8A8
color14 #3DD4D4
#: white
color7  #B3B3B3
color15 #FFFFFF