# vim:ft=kitty
#: This is a template that can be used to create new kitty themes.
#: Theme files should start with a metadata block consisting of
#: lines beginning with ##. All metadata fields are optional.

## name: Box
## author: D3vil0p3r
## license: GPLv3
## blurb: Hack The Box inspired colorscheme.

#: All the settings below are colors, which you can choose to modify, or use the
#: defaults. You can also add non-color based settings if needed but note that
#: these will not work with using kitty @ set-colors with this theme. For a
#: reference on what these settings do see https://sw.kovidgoyal.net/kitty/conf/

#: OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color   system


#: The basic colors
foreground                      hsl(80, 100%, 50%)
selection_foreground            hsl(80, 100%, 50%)
background                      hsl(0, 0%, 8%)
selection_background            hsl(200, 80%, 50%)


#: Cursor colors
cursor                          hsl(80, 100%, 50%)
cursor_text_color               hsl(0, 0%, 7%)


#: URL underline color when hovering with mouse
url_color                       hsl(164, 79%, 54%)


#: kitty window border colors and terminal bell colors
active_border_color             hsl(90, 80%, 50%)
inactive_border_color           hsl(0, 0%, 80%)
bell_border_color               hsl(20, 80%, 50%)
visual_bell_color               none

#: Tab bar colors
active_tab_foreground           hsl(0, 0%, 0%)
active_tab_background           hsl(80, 100%, 50%)
inactive_tab_foreground         hsl(60, 100%, 50%)
inactive_tab_background         hsl(200, 80%, 50%)
tab_bar_background              none
tab_bar_margin_color            none


#: Colors for marks (marked text in the terminal)

mark1_foreground black
mark1_background hsl(170, 50%, 70%)
mark2_foreground black
mark2_background hsl(20, 50%, 70%)
mark3_foreground black
mark3_background hsl(320, 50%, 70%)


#: The basic 16 colors
#: black
color0  hsl(0, 0%, 0%)
color8  hsl(0, 0%, 30%)
#: red
color1  hsl(0, 80%, 40%)
color9  hsl(0, 80%, 60%)
#: green
color2  hsl(140, 80%, 40%)
color10 hsl(140, 80%, 60%)
#: yellow
color3  hsl(60, 80%, 50%)
color11 hsl(60, 80%, 70%)
#: blue
color4  hsl(220, 80%, 40%)
color12 hsl(220, 80%, 60%)
#: magenta
color5  hsl(290, 80%, 40%)
color13 hsl(290, 80%, 60%)
#: cyan
color6  hsl(180, 80%, 40%)
color14 hsl(180, 80%, 60%)
#: white
color7  hsl(0, 0%, 70%)
color15 hsl(0, 0%, 100%)